SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

USE `db_gfinanciero` ;
--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `CB0003`
--
ALTER TABLE `CB0003`
  ADD CONSTRAINT `N_CTA_B_FK` FOREIGN KEY (`COD_BAN`,`N_CTA_B`) REFERENCES `CB0002` (`COD_BAN`, `N_CTA_B`);

--
-- Filtros para la tabla `CB0004`
--
ALTER TABLE `CB0004`
  ADD CONSTRAINT `CB04_N_CTA_B_FK` FOREIGN KEY (`COD_BAN`,`N_CTA_B`) REFERENCES `CB0002` (`COD_BAN`, `N_CTA_B`);

--
-- Filtros para la tabla `CB0010`
--
ALTER TABLE `CB0010`
  ADD CONSTRAINT `CB10_COD_CLI_FK` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `CB0020`
--
ALTER TABLE `CB0020`
  ADD CONSTRAINT `CB20_COD_PRO_FK` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `CC0002`
--
ALTER TABLE `CC0002`
  ADD CONSTRAINT `CC02_COD_CLI_FK` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `CC0010`
--
ALTER TABLE `CC0010`
  ADD CONSTRAINT `FK_CC0010_1` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `CC0011`
--
ALTER TABLE `CC0011`
  ADD CONSTRAINT `FK_CC0011_2` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE,
  ADD CONSTRAINT `INGRESO_FK` FOREIGN KEY (`NUM_ING`) REFERENCES `CB0010` (`NUM_ING`) ON UPDATE CASCADE;


--
-- Filtros para la tabla `COSSUBCEN`
--
ALTER TABLE `COSSUBCEN`
  ADD CONSTRAINT `COSSUBCEN_ibfk_1` FOREIGN KEY (`COD_CEN`) REFERENCES `COSCENTRO` (`COD_CEN`);

--
-- Filtros para la tabla `CP0002`
--
ALTER TABLE `CP0002`
  ADD CONSTRAINT `FK_CP0002_1` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `CP0010`
--
ALTER TABLE `CP0010`
  ADD CONSTRAINT `FK_CP0010_1` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `CP0011`
--
ALTER TABLE `CP0011`
  ADD CONSTRAINT `EGRESO_FK` FOREIGN KEY (`NUM_EGR`) REFERENCES `CB0020` (`NUM_EGR`) ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_CP0011_2` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `IG0020`
--
ALTER TABLE `IG0020`
  ADD CONSTRAINT `COD_LIN_FK` FOREIGN KEY (`COD_LIN`) REFERENCES `IG0001` (`COD_LIN`),
  ADD CONSTRAINT `COD_MAR_FK` FOREIGN KEY (`COD_MAR`) REFERENCES `IG0003` (`COD_MAR`),
  ADD CONSTRAINT `COD_TIP_FK` FOREIGN KEY (`COD_TIP`) REFERENCES `IG0002` (`COD_TIP`);

--
-- Filtros para la tabla `IG0022`
--
ALTER TABLE `IG0022`
  ADD CONSTRAINT `COD_ART_FK` FOREIGN KEY (`COD_ART`) REFERENCES `IG0020` (`COD_ART`),
  ADD CONSTRAINT `COD_bod_FK` FOREIGN KEY (`COD_BOD`) REFERENCES `IG0021` (`COD_BOD`);

--
-- Filtros para la tabla `IG0026`
--
ALTER TABLE `IG0026`
  ADD CONSTRAINT `NUM_ING_FK` FOREIGN KEY (`COD_BOD`,`NUM_ING`) REFERENCES `IG0025` (`COD_BOD`, `NUM_ING`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `IG0028`
--
ALTER TABLE `IG0028`
  ADD CONSTRAINT `NUM_EGR_FK` FOREIGN KEY (`COD_BOD`,`NUM_EGR`) REFERENCES `IG0027` (`COD_BOD`, `NUM_EGR`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `IG0040`
--
ALTER TABLE `IG0040`
  ADD CONSTRAINT `ATIENDE_FK` FOREIGN KEY (`ATIENDE`) REFERENCES `MG0033` (`COD_EMP`),
  ADD CONSTRAINT `COD_CLI_FK` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `IG0041`
--
ALTER TABLE `IG0041`
  ADD CONSTRAINT `IG41_ATIENDE_FK` FOREIGN KEY (`COD_EMP`) REFERENCES `MG0033` (`COD_EMP`),
  ADD CONSTRAINT `IG41_COD_ART_FK` FOREIGN KEY (`COD_ART`) REFERENCES `IG0020` (`COD_ART`),
  ADD CONSTRAINT `IG41_COD_CLI_FK` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE,
  ADD CONSTRAINT `NUM_COT_FK` FOREIGN KEY (`NUM_COT`) REFERENCES `IG0040` (`NUM_COT`);

--
-- Filtros para la tabla `IG0050`
--
ALTER TABLE `IG0050`
  ADD CONSTRAINT `IG50_COD_PRO_FK` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `IG0051`
--
ALTER TABLE `IG0051`
  ADD CONSTRAINT `FK_IG0051_2` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE,
  ADD CONSTRAINT `P_T_PED_FK` FOREIGN KEY (`COD_PTO`,`TIP_PED`,`NUM_PED`) REFERENCES `IG0050` (`COD_PTO`, `TIP_PED`, `NUM_PED`) ON UPDATE CASCADE;


--
-- Filtros para la tabla `IG0054`
--
ALTER TABLE `IG0054`
  ADD CONSTRAINT `IG54_COD_PRO_FK` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `IG0055`
--
ALTER TABLE `IG0055`
  ADD CONSTRAINT `FK_IG0055_1` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `IG0056`
--
ALTER TABLE `IG0056`
  ADD CONSTRAINT `C_T_DEV_FK` FOREIGN KEY (`COD_PTO`,`TIP_DEV`,`NUM_DEV`) REFERENCES `IG0055` (`COD_PTO`, `TIP_DEV`, `NUM_DEV`) ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_IG0056_3` FOREIGN KEY (`COD_PRO`) REFERENCES `MG0032` (`COD_PRO`) ON UPDATE CASCADE,
  ADD CONSTRAINT `IG56_COD_ART_FK` FOREIGN KEY (`COD_ART`) REFERENCES `IG0020` (`COD_ART`);


--
-- Filtros para la tabla `IG0060`
--
ALTER TABLE `IG0060`
  ADD CONSTRAINT `FK_IG0060_3` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE,
  ADD CONSTRAINT `IG60_COD_MOT_FK` FOREIGN KEY (`COD_MOT`) REFERENCES `MG0041` (`COD_MOT`);

--
-- Filtros para la tabla `IG0061`
--
ALTER TABLE `IG0061`
  ADD CONSTRAINT `FK_IG0061_3` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE,
  ADD CONSTRAINT `IG61_C_T_DEV_FK` FOREIGN KEY (`COD_PTO`,`TIP_DEV`,`NUM_DEV`) REFERENCES `IG0060` (`COD_PTO`, `TIP_DEV`, `NUM_DEV`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `IG61_COD_ART_FK` FOREIGN KEY (`COD_ART`) REFERENCES `IG0020` (`COD_ART`);


--
-- Filtros para la tabla `MG0016`
--
ALTER TABLE `MG0016`
  ADD CONSTRAINT `COD_PTO_FK` FOREIGN KEY (`COD_PTO`) REFERENCES `MG0015` (`COD_PTO`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `RE0002`
--
ALTER TABLE `RE0002`
  ADD CONSTRAINT `RE0002_ibfk_1` FOREIGN KEY (`IDS_REN`) REFERENCES `RE0001` (`IDS_REN`);

--
-- Filtros para la tabla `VC010101`
--
ALTER TABLE `VC010101`
  ADD CONSTRAINT `VC01_COD_CLI_FK` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE;

--
-- Filtros para la tabla `VD010101`
--
ALTER TABLE `VD010101`
  ADD CONSTRAINT `VD01_COD_ART_FK` FOREIGN KEY (`COD_ART`) REFERENCES `IG0020` (`COD_ART`),
  ADD CONSTRAINT `VD01_COD_CLI_FK` FOREIGN KEY (`COD_CLI`) REFERENCES `MG0031` (`COD_CLI`) ON UPDATE CASCADE,
  ADD CONSTRAINT `VD01_NUM_NOF_FK` FOREIGN KEY (`COD_PTO`,`COD_CAJ`,`TIP_NOF`,`NUM_NOF`) REFERENCES `VC010101` (`COD_PTO`, `COD_CAJ`, `TIP_NOF`, `NUM_NOF`) ON UPDATE CASCADE;
COMMIT;