<?php

use app\modules\academico\models\DistributivoAcademico;
use yii\helpers\Html;
use kartik\grid\GridView;
use app\modules\academico\Module as academico;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<?php echo $this->render('reportematrizdistributivo_search', ['model' => $searchModel]); ?>


<?=

GridView::widget([
    'dataProvider' => $dataProvider,
    //'filterModel' => $searchModel,
    'pjax' => true,
    //  'autoXlFormat' => true,
    // 'showPageSummary' => true,
    'striped' => false,
    'panel' => [
        'type' => 'primary',
        'heading' => 'Matriz Distributivo Docentes'
    ],
    'exportConfig' => [
        //GridView::CSV => ['label' => 'Save as CSV'],
        // GridView::HTML => [// html settings],
        /*   GridView::PDF => [
          'label' => 'PDF',
          // 'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
          'iconOptions' => ['class' => 'text-danger'],
          'showHeader' => true,
          'showPageSummary' => false,
          'showFooter' => true,
          'showCaption' => true,
          'filename' => 'Distributivo',

          'config' => [
          'options' => [
          'title' => "pr",
          'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
          'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
          ],
          ],
          ], */
        GridView::EXCEL => [
            'label' => Yii::t('kvgrid', 'Excel'),
            //'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
            'iconOptions' => ['class' => 'text-success'],
            'showHeader' => true,
            'showFooter' => true,
            'showCaption' => true,
            'filename' => Yii::t('kvgrid', 'Matriz-Distributivo'),
            'alertMsg' => Yii::t('kvgrid', 'The EXCEL export file will be generated for download.'),
            'options' => ['title' => Yii::t('kvgrid', 'Microsoft Excel 95+')],
            'mime' => 'application/vnd.ms-excel',
            'config' => [
                'worksheet' => Yii::t('kvgrid', 'ExportWorksheet'),
                'cssFile' => ''
            ]
        ],
    ],
    'export' => [
        'showConfirmAlert' => false,
        'target' => GridView::TARGET_BLANK,
    ],
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'attribute' => 'codigo_ies',
            'header' => academico::t("Academico", "CODIGO_IES"),
            'value' => 'codigo_ies',
        ],
        [
            'attribute' => 'tipo_identificacion',
            'header' => academico::t("Academico", "TIPO DE IDENTIFICACIÓN"),
            'value' => 'tipo_identificacion',
        ],
        [
            'attribute' => 'no_cedula',
            'header' => academico::t("Academico", "IDENTIFICACIÓN"),
            'value' => 'no_cedula',
        ],
        [
            'attribute' => 'docente',
            'header' => academico::t("Academico", "DOCENTE"),
            'value' => 'docente',
        ],
        [
            'attribute' => 'pro_num_contrato',
            'header' => academico::t("Academico", "NUMERO DE DOCUMENTO"),
            'value' => 'pro_num_contrato',
        ],
        ['class' => 'kartik\grid\FormulaColumn',
            'attribute' => 'hora_clase',
            'header' => academico::t("Academico", "HORAS CLASE"),
            'value' => 'hora_clase',
            
        ],
        [
            'attribute' => 'hora_tutorias',
            'header' => academico::t("Academico", "HORAS TUTORIAS"),
            'value' => 'hora_tutorias',
        ],
        
          [
            'attribute' => 'hora_administrativa',
            'header' => academico::t("Academico", "HORAS ADMINISTRATIVAS"),
           'value' => function ($model, $key, $index, $widget) {
               
                return $model['ddoc_horas'] - ($model['hora_clase'] +$model['hora_otras_actividades']+ $model['hora_ivestigacion']+ $model['hora_tutorias']+ $model['hora_vinculacion']);
            },
        ],
        [
            'attribute' => 'hora_ivestigacion',
            'header' => academico::t("Academico", "HORAS INVESTIGACION"),
            'value' => 'hora_investigacion',
        ],
        [
            'attribute' => 'hora_vinculacion',
            'header' => academico::t("Academico", "HORAS VINCULACION"),
            'value' => 'hora_vinculacion',
        ],
        [
            'attribute' => 'hora_otras_actividades',
            'header' => academico::t("Academico", "HORAS OTRAS ACTIVIDADES"),
            'value' => 'hora_otras_actividades',
        ],
                   
        [
            'attribute' => 'comun',
            'header' => academico::t("Academico", "HORAS CLASE NIVEL TECNICO"),
            'value' => 'comun',
            'visible' => false,
        ],
        [
            'attribute' => 'tercel_nivel',
            'header' => academico::t("Academico", "HORAS CLASE TERCER NIVEL"),
            'value' => 'tercel_nivel',
        ],
        [
            'attribute' => 'cuarto_nivel',
            'header' => academico::t("Academico", "HORAS CLASE CUARTO NIVEL"),
            'value' => 'cuarto_nivel',
        ],
   
        [
            'attribute' => 'comun',
            'header' => academico::t("Academico", "CALIFICACION ACTIVIDADES DOCENCIA"),
            'value' => 'comun',
        ],
        [
            'attribute' => 'comun',
            'header' => academico::t("Academico", "CALIFICACION ACTIVIDADES INVESTIGACION"),
            'value' => 'comun',
        ],
        [
            'attribute' => 'comun',
            'header' => academico::t("Academico", "CALIFICACION ACTIVIDADES DIRECCION GESTION ACADEMICA"),
            'value' => 'comun',
        ],
    ],
]);
?>

