<?php

use app\modules\academico\models\DistributivoAcademico;
use yii\helpers\Html;
use kartik\grid\GridView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<?php echo $this->render('_searchdistributivo', ['model' => $searchModel]); ?>


<?=

GridView::widget([
    'dataProvider' => $dataProvider,
    //'filterModel' => $searchModel,
    'pjax' => true,
  //  'autoXlFormat' => true,
    // 'showPageSummary' => true,
    'panel' => [
        'type' => 'primary',
        'heading' => 'Reporte Distributivo'
    ],
    'exportConfig' => [
            //GridView::CSV => ['label' => 'Save as CSV'],
            // GridView::HTML => [// html settings],
         /*   GridView::PDF => [
                'label' => 'PDF',
               // 'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
                'iconOptions' => ['class' => 'text-danger'],
                'showHeader' => true,
                'showPageSummary' => false,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => 'Distributivo',
               
                'config' => [
               'options' => [
                'title' => "pr",
                'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
                'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
            ],
                ],
            ],*/
        GridView::EXCEL => [
        'label' => Yii::t('kvgrid', 'Excel'),
        //'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
        'iconOptions' => ['class' => 'text-success'],
        'showHeader' => true,
        'showPageSummary' => false,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The EXCEL export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'Microsoft Excel 95+')],
        'mime' => 'application/vnd.ms-excel',
        'config' => [
            'worksheet' => Yii::t('kvgrid', 'ExportWorksheet'),
            'cssFile' => ''
        ]
    ],
        
        ],
    'export' => [
        'showConfirmAlert' => false,
        'target' => GridView::TARGET_BLANK,
        
    ],
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'docente',
        'no_cedula',
        'titulo_tercel_nivel',
        'titulo_cuarto_nivel',
        'correo',
        'tiempo_dedicacion',
        'desempeno',
        'materia',
        'nivel',
        'credito',
        'horas_por_credito',
        'total_horas_dictar',
    ],
]);
?>

