<?php

use app\modules\academico\models\DistributivoAcademico;
use yii\helpers\Html;
use kartik\grid\GridView;
use app\modules\academico\Module as academico;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<?php echo $this->render('_searchdistributivo_posgrado', ['model' => $searchModel]); ?>


<?=

GridView::widget([
    'dataProvider' => $dataProvider,
    //'filterModel' => $searchModel,
    'pjax' => true,
    //  'autoXlFormat' => true,
    'showPageSummary' => true,
    'striped' => false,
    'panel' => [
        'type' => 'primary',
        'heading' => 'Reporte Distributivo Posgrado'
    ],
    'exportConfig' => [
        //GridView::CSV => ['label' => 'Save as CSV'],
        // GridView::HTML => [// html settings],
        /*   GridView::PDF => [
          'label' => 'PDF',
          // 'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
          'iconOptions' => ['class' => 'text-danger'],
          'showHeader' => true,
          'showPageSummary' => false,
          'showFooter' => true,
          'showCaption' => true,
          'filename' => 'Distributivo',

          'config' => [
          'options' => [
          'title' => "pr",
          'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
          'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
          ],
          ],
          ], */
        GridView::EXCEL => [
            'label' => Yii::t('kvgrid', 'Excel'),
            //'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
            'iconOptions' => ['class' => 'text-success'],
            'showHeader' => true,
           
            'showFooter' => true,
            'showCaption' => true,
            'filename' => Yii::t('kvgrid', 'grid-export'),
            'alertMsg' => Yii::t('kvgrid', 'The EXCEL export file will be generated for download.'),
            'options' => ['title' => Yii::t('kvgrid', 'Microsoft Excel 95+')],
            'mime' => 'application/vnd.ms-excel',
            'config' => [
                'worksheet' => Yii::t('kvgrid', 'ExportWorksheet'),
                'cssFile' => ''
            ]
        ],
    ],
    'export' => [
        'showConfirmAlert' => false,
        'target' => GridView::TARGET_BLANK,
    ],
    'columns' => [
       
        [
            'attribute' => 'docente',
            'header' => academico::t("Academico", "Profesor"),
            'value' => 'docente',
            'group' => true,
        ],
        
        [
            'attribute' => 'titulo_tercel_nivel',
            'header' => academico::t("Academico", "3er. Nivel"),
            'value' => 'titulo_tercel_nivel',
            'group' => true,
        ],
        [
            'attribute' => '4to Nivel',
            'header' => academico::t("Academico", "4to Nivel"),
            'value' => 'titulo_cuarto_nivel',
            'group' => true,
        ],
        [
            'attribute' => 'maestria',
            'header' => academico::t("Academico", "Maestría "),
            'value' => 'maestria',
            'group' => true,
        ],
        [
            'attribute' => 'paralelo',
            'header' => academico::t("Academico", "Grupo Paralelo"),
            'value' => 'paralelo',
            'group' => true,
        ],
         
        [
            'attribute' => 'materia',
            'header' => academico::t("Academico", "Materias"),
            'value' => 'materia',
          
        ],
        [
            'attribute' => 'dias',
            'header' => academico::t("Academico", "Días"),
            'value' => 'dias',
            'group' => true, // enable grouping
        
        ],
        [
            'attribute' => 'hora',
            'header' => academico::t("Academico", "Hora"),
            'value' => 'hora',
        //    'pageSummary' => 'Page Summary',
           
        ],
        [
            'attribute' => 'num_est',
            'header' => academico::t("Academico", "No. Estudiantes"),
            'value' => 'num_est',
        //    'pageSummary' => 'Page Summary',
           
        ],
         
        [
            'attribute' => 'total_horas_dictar',
            'header' => academico::t("Academico", "Total  Horas  a dictar"),
            'value' => 'total_horas_dictar',
        //    'pageSummary' => 'Page Summary',
           
        ],
        [
            'attribute' => 'modalidad',
            'header' => academico::t("Academico", "Modalidad"),
            'value' => 'modalidad',
           // 'pageSummary' => 'Page Summary',
           
        ],
        [
            'attribute' => 'aula',
            'header' => academico::t("Academico", "Aula"),
            'value' => 'aula',
           // 'pageSummary' => 'Page Summary',
           
        ],
        [
            'attribute' => 'credito',
            'header' => academico::t("Academico", "Total  crédito"),
            'value' => 'credito',
           // 'pageSummary' => 'Page Summary',
           
        ],
    ],
]);
?>

